### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by kostafey** [jonase/lein-kibit#8]
`lein-kibit "0.1.2"`
```
Exception in thread "main" java.lang.StackOverflowError, compiling:(/tmp/form-init6260368410046579919.clj:1:72)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.StackOverflowError
	at clojure.core.logic$walk_STAR_$fn__1620.invoke(logic.clj:231)
	at clojure.core.logic$eval1821$fn__1822.invoke(logic.clj:984)
	at clojure.core.logic.protocols$eval277$fn__278$G__268__285.invoke(protocols.clj:55)
	at clojure.core.logic$walk_STAR_.invoke(logic.clj:229)
	at clojure.core.logic$walk_STAR_$fn__1620.invoke(logic.clj:233)
	at clojure.core.logic$eval1821$fn__1822.invoke(logic.clj:984)
	at clojure.core.logic.protocols$eval277$fn__278$G__268__285.invoke(protocols.clj:55)
	at clojure.core.logic$walk_STAR_.invoke(logic.clj:229)
	at clojure.core.logic$walk_STAR_$fn__1620.invoke(logic.clj:233)
	at clojure.core.logic$eval1821$fn__1822.invoke(logic.clj:984)
	at clojure.core.logic.protocols$eval277$fn__278$G__268__285.invoke(protocols.clj:55)
	at clojure.core.logic$walk_STAR_.invoke(logic.clj:229)
	at clojure.core.logic$walk_STAR_$fn__1620.invoke(logic.clj:233)
	at clojure.core.logic$eval1821$fn__1822.invoke(logic.clj:984)
	at clojure.core.logic.protocols$eval277$fn__278$G__268__285.invoke(protocols.clj:55)
	at clojure.core.logic$walk_STAR_.invoke(logic.clj:229)
	at clojure.core.logic$walk_STAR_$fn__1620.invoke(logic.clj:233)
	at clojure.core.logic$eval1821$fn__1822.invoke(logic.clj:984)
	at clojure.core.logic.protocols$eval277$fn__278$G__268__285.invoke(protocols.clj:55)
	at clojure.core.logic$walk_STAR_.invoke(logic.clj:229)
	at clojure.core.logic$walk_STAR_$fn__1620.invoke(logic.clj:233)
	at clojure.core.logic$eval1821$fn__1822.invoke(logic.clj:984)
	at clojure.core.logic.protocols$eval277$fn__278$G__268__285.invoke(protocols.clj:55)
```

**Comment by danielcompton** [comment]
Looks like a dupe of https://github.com/jonase/kibit/issues/78 ?
